 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/identifiers", type: :request do
  # Identifier. As you add validations to Identifier, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Identifier.create! valid_attributes
      get identifiers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      identifier = Identifier.create! valid_attributes
      get identifier_url(identifier)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_identifier_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      identifier = Identifier.create! valid_attributes
      get edit_identifier_url(identifier)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Identifier" do
        expect {
          post identifiers_url, params: { identifier: valid_attributes }
        }.to change(Identifier, :count).by(1)
      end

      it "redirects to the created identifier" do
        post identifiers_url, params: { identifier: valid_attributes }
        expect(response).to redirect_to(identifier_url(Identifier.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Identifier" do
        expect {
          post identifiers_url, params: { identifier: invalid_attributes }
        }.to change(Identifier, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post identifiers_url, params: { identifier: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested identifier" do
        identifier = Identifier.create! valid_attributes
        patch identifier_url(identifier), params: { identifier: new_attributes }
        identifier.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the identifier" do
        identifier = Identifier.create! valid_attributes
        patch identifier_url(identifier), params: { identifier: new_attributes }
        identifier.reload
        expect(response).to redirect_to(identifier_url(identifier))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        identifier = Identifier.create! valid_attributes
        patch identifier_url(identifier), params: { identifier: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested identifier" do
      identifier = Identifier.create! valid_attributes
      expect {
        delete identifier_url(identifier)
      }.to change(Identifier, :count).by(-1)
    end

    it "redirects to the identifiers list" do
      identifier = Identifier.create! valid_attributes
      delete identifier_url(identifier)
      expect(response).to redirect_to(identifiers_url)
    end
  end
end
