 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/npi_records", type: :request do
  # NpiRecord. As you add validations to NpiRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NpiRecord.create! valid_attributes
      get npi_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      npi_record = NpiRecord.create! valid_attributes
      get npi_record_url(npi_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_npi_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      npi_record = NpiRecord.create! valid_attributes
      get edit_npi_record_url(npi_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NpiRecord" do
        expect {
          post npi_records_url, params: { npi_record: valid_attributes }
        }.to change(NpiRecord, :count).by(1)
      end

      it "redirects to the created npi_record" do
        post npi_records_url, params: { npi_record: valid_attributes }
        expect(response).to redirect_to(npi_record_url(NpiRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NpiRecord" do
        expect {
          post npi_records_url, params: { npi_record: invalid_attributes }
        }.to change(NpiRecord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post npi_records_url, params: { npi_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested npi_record" do
        npi_record = NpiRecord.create! valid_attributes
        patch npi_record_url(npi_record), params: { npi_record: new_attributes }
        npi_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the npi_record" do
        npi_record = NpiRecord.create! valid_attributes
        patch npi_record_url(npi_record), params: { npi_record: new_attributes }
        npi_record.reload
        expect(response).to redirect_to(npi_record_url(npi_record))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        npi_record = NpiRecord.create! valid_attributes
        patch npi_record_url(npi_record), params: { npi_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested npi_record" do
      npi_record = NpiRecord.create! valid_attributes
      expect {
        delete npi_record_url(npi_record)
      }.to change(NpiRecord, :count).by(-1)
    end

    it "redirects to the npi_records list" do
      npi_record = NpiRecord.create! valid_attributes
      delete npi_record_url(npi_record)
      expect(response).to redirect_to(npi_records_url)
    end
  end
end
