 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/taxonomies", type: :request do
  # Taxonomy. As you add validations to Taxonomy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Taxonomy.create! valid_attributes
      get taxonomies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      taxonomy = Taxonomy.create! valid_attributes
      get taxonomy_url(taxonomy)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_taxonomy_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      taxonomy = Taxonomy.create! valid_attributes
      get edit_taxonomy_url(taxonomy)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Taxonomy" do
        expect {
          post taxonomies_url, params: { taxonomy: valid_attributes }
        }.to change(Taxonomy, :count).by(1)
      end

      it "redirects to the created taxonomy" do
        post taxonomies_url, params: { taxonomy: valid_attributes }
        expect(response).to redirect_to(taxonomy_url(Taxonomy.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Taxonomy" do
        expect {
          post taxonomies_url, params: { taxonomy: invalid_attributes }
        }.to change(Taxonomy, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post taxonomies_url, params: { taxonomy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested taxonomy" do
        taxonomy = Taxonomy.create! valid_attributes
        patch taxonomy_url(taxonomy), params: { taxonomy: new_attributes }
        taxonomy.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the taxonomy" do
        taxonomy = Taxonomy.create! valid_attributes
        patch taxonomy_url(taxonomy), params: { taxonomy: new_attributes }
        taxonomy.reload
        expect(response).to redirect_to(taxonomy_url(taxonomy))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        taxonomy = Taxonomy.create! valid_attributes
        patch taxonomy_url(taxonomy), params: { taxonomy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested taxonomy" do
      taxonomy = Taxonomy.create! valid_attributes
      expect {
        delete taxonomy_url(taxonomy)
      }.to change(Taxonomy, :count).by(-1)
    end

    it "redirects to the taxonomies list" do
      taxonomy = Taxonomy.create! valid_attributes
      delete taxonomy_url(taxonomy)
      expect(response).to redirect_to(taxonomies_url)
    end
  end
end
